---
title: "Основы обработки данных с помощью R и Dplyr"
format: 
  md:
    output-file: README.md
---

## Цель работы

 1. Развить практические навыки использования языка программирования R для
 обработки данных
 2. Закрепить знания базовых типов данных языка R
 3. Развить практические навыки использования функций обработки данных пакета
 dplyr – функции 
select(), filter(), mutate(), arrange(), group_by()

## Исходные данные

1. Rstudio Desktop
2. Наше рабочее окружение
       
## План

1. Проанализировать встроенный в пакет dplyr набор данных языка R
2. Ответить на вопросы

## Шаги: 

```{r}
sessionInfo()
``` 

Проанализировать встроенные в пакет nycflights13 наборы данных с помощью
языка R и ответить на вопросы:

1. Сколько встроенных в пакет nycflights13 датафреймов?

>data(package = "nycflights13")

Data sets in package ‘nycflights13’:

airlines                Airline names.
airports                Airport metadata
flights                 Flights data
planes                  Plane metadata.
weather                 Hourly weather data

2. Сколько строк в каждом датафрейме?


> nrow(airlines) 
[1] 16

> nrow(airports) 
[1] 1458

> nrow(flights) 
[1] 336776

> nrow(planes) 
[1] 3322

> nrow(weather) 
[1] 26115

3. Сколько столбцов в каждом датафрейме?

> ncol(airlines) 
[1] 2

> ncol(airports) 
[1] 8

> ncol(flights) 
[1] 19

> ncol(planes) 
[1] 9

> ncol(weather) 
[1] 15

4. Как просмотреть примерный вид датафрейма?

> airlines %>% glimpse
Rows: 16
Columns: 2
$ carrier <chr> "9E", "AA", "AS", "B6", "DL", "EV", "F9", "FL", "HA", "MQ", "OO",…
$ name    <chr> "Endeavor Air Inc.", "American Airlines Inc.", "Alaska Airlines I…

5. Сколько компаний-перевозчиков (carrier) учитывают эти наборы данных (представлено в наборах данных)?

> airlines %>% distinct(carrier) %>% nrow()
[1] 16

6. Сколько рейсов принял аэропорт John F Kennedy Intl в мае?

> flights %>% filter(origin == "JFK", month == 5) %>% count()
1  9397

7. Какой самый северный аэропорт?

> airports %>% arrange(desc(lat)) %>% select(name) %>% head(1)
1 Dillant Hopkins Airport

8. Какой аэропорт самый высокогорный (находится выше всех над уровнем моря)?

> airports %>% arrange(desc(alt)) %>% select(name) %>% head(1)
1 Telluride

9. Какие бортовые номера у самых старых самолетов?

> planes %>% arrange(year) %>% head(1) %>% select(tailnum, year)
  tailnum  year
1 N381AA   1956


10. Какая средняя температура воздуха была в сентябре в аэропорту John FKennedy Intl (в градусах Цельсия).

> weather %>% filter(origin == "JFK", month == 9) %>% summarise(avg_temp_c = mean((temp - 32) * 5/9, na.rm = TRUE))
  avg_temp_c
1       19.4

11. Самолеты какой авиакомпании совершили больше всего вылетов в июне?Данные
i2z1.ddslab.ru 3

> flights %>% filter(month == 6) %>% count(carrier, sort = TRUE) %>% left_join(airlines, by = "carrier") %>% head(1)
  carrier     n name             
1 UA       4975 United Air Lines Inc.

12. Самолеты какой авиакомпании задерживались чаще других в 2013 году?


