---
title: "Введение в R"
format: 
  md:
    output-file: README.md
---

## Цель работы

 1. Развить практические навыки использования языка программирования R для
 обработки данных
 2. Развить навыки работы в Rstudio IDE:
 установка пакетов
 работа с проектами в Rstudio
 настройка и работа с Git
 3. Закрепить знания базовых типов данных языка R и простейших операций с ними

## Исходные данные

1. Rstudio Desktop
2. Наше рабочее окружение
       
## План

 Запустить подкурсы и выполнить:
  базовые структурные блоки (Basic Building Blocks)
  рабочие пространства и файлы (Workspace and Files)
  последовательности чисел (Sequences of Numbers)
  векторы (Vectors)
  пропущенные значения (Missing Values)    

## Шаги: 
sessionInfo()
R version 4.5.1 (2025-06-13 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 11 x64 (build 26100)

Matrix products: default
  LAPACK version 3.12.1

locale:
[1] LC_COLLATE=Russian_Russia.utf8  LC_CTYPE=Russian_Russia.utf8   
[3] LC_MONETARY=Russian_Russia.utf8 LC_NUMERIC=C                   
[5] LC_TIME=Russian_Russia.utf8    

time zone: Europe/Moscow
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.5.1 tools_4.5.1   

## Basic Building Blocks

Type 5 + 7 and press Enter.

> 5 + 7
[1] 12

| To assign the result of 5 + 7 to a new variable called x, you type x <- 5 +
| 7. This can be read as 'x gets 5 plus 7'. Give it a try now.


```{r}
x <- 5 + 7
```

| You are amazing!

  |==============                                                      |  21%

| To view the contents of the variable x, just type x and press Enter. Try it
| now.

> x
[1] 12

| You nailed it! Good job!

  |==================                                                  |  26%
| Now, store the result of x - 3 in a new variable called y.

> y <- x - 3

| That's correct!

  |====================                                                |  29%
| What is the value of y? Type y to find out.

> y
[1] 9

| The easiest way to create a vector is with the c() function, which stands
| for 'concatenate' or 'combine'. To create a vector containing the numbers
| 1.1, 9, and 3.14, type c(1.1, 9, 3.14). Try it now and store the result in
| a variable called z.

> c(1.1, 9, 3.14)
[1] 1.10 9.00 3.14


| Inputting z <- c(1.1, 9, 3.14) will assign the vector (1.1, 9, 3.14) to a
| new variable called z. Including single spaces after the commas in the
| vector is not required, but helps make your code less cluttered and more
| readable.

> z <- c(1.1, 9, 3.14)

| That's the answer I was looking for.

  |=========================                                           |  37%
| Anytime you have questions about a particular function, you can access R's
| built-in help files via the `?` command. For example, if you want more
| information on the c() function, type ?c without the parentheses that
| normally follow a function name. Give it a try.

> ?c

| All that hard work is paying off!

  |===========================                                         |  39%
| Type z to view its contents. Notice that there are no commas separating the
| values in the output.

> z
[1] 1.10 9.00 3.14

| You got it!

  |=============================                                       |  42%
| You can combine vectors to make a new vector. Create a new vector that
| contains z, 555, then z again in that order. Don't assign this vector to a
| new variable, so that we can just see the result immediately.

> c(z, 555, z)
[1]   1.10   9.00   3.14 555.00   1.10   9.00   3.14

| That's correct!

  |==============================                                      |  45%
| Numeric vectors can be used in arithmetic expressions. Type the following
| to see what happens: z * 2 + 100.

> z * 2 + 100
[1] 102.20 118.00 106.28

| Excellent work!

  |================================                                    |  47%
  
| Take the square root of z - 1 and assign it to a new variable called
| my_sqrt.

> my_sqrt <- sqrt(z-1)

| You are doing so well!

  |======================================                              |  55%
| Before we view the contents of the my_sqrt variable, what do you think it
| contains?

1: a vector of length 3
2: a vector of length 0 (i.e. an empty vector)
3: a single number (i.e a vector of length 1)

Выбор: 1

| Great job!

  |=======================================                             |  58%
| Print the contents of my_sqrt.

> my_sqrt
[1] 0.3162278 2.8284271 1.4628739

| Now, create a new variable called my_div that gets the value of z divided
| by my_sqrt.

> my_div <- z/my_sqrt

| You got it right!

  |=============================================                       |  66%
| Which statement do you think is true?

1: my_div is undefined
2: my_div is a single number (i.e a vector of length 1)
3: The first element of my_div is equal to the first element of z divided by the first element of my_sqrt, and so on...

Выбор: 3

| Keep working like that and you'll get there!

  |===============================================                     |  68%
| Go ahead and print the contents of my_div.

> my_div
[1] 3.478505 3.181981 2.146460

| To see another example of how this vector 'recycling' works, try adding
| c(1, 2, 3, 4) and c(0, 10). Don't worry about saving the result in a new
| variable.

> 
> c(1, 2, 3, 4) + c(0, 10)
[1]  1 12  3 14

| Try c(1, 2, 3, 4) + c(0, 10, 100) for an example.

> c(1, 2, 3, 4) + c(0, 10, 100)
[1]   1  12 103   4
Предупреждение:
В c(1, 2, 3, 4) + c(0, 10, 100) :
  длина большего объекта не является произведением длины меньшего объекта

| That's the answer I was looking for.

  |===========================================================         |  87%
  
| In many programming environments, the up arrow will cycle through previous
| commands. Try hitting the up arrow on your keyboard until you get to this
| command (z * 2 + 100), then change 100 to 1000 and hit Enter. If the up
| arrow doesn't work for you, just type the corrected command.

> z * 2 + 1000
[1] 1002.20 1018.00 1006.28

| You can type the first two letters of the variable name, then hit the Tab
| key (possibly more than once). Most programming environments will provide a
| list of variables that you've created that begin with 'my'. This is called
| auto-completion and can be quite handy when you have many variables in your
| workspace. Give it a try. (If auto-completion doesn't work for you, just
| type my_div and press Enter.)

> my_div
[1] 3.478505 3.181981 2.146460

| Nice work!

  |====================================================================| 100%
  
| In this lesson, you'll learn how to examine your local workspace in R and
| begin to explore the relationship between your workspace and the file
| system of your machine.

...

  |==                                                                  |   3%
| Because different operating systems have different conventions with regards
| to things like file paths, the outputs of these commands may vary across
| machines.

...

  |===                                                                 |   5%
| However it's important to note that R provides a common API (a common set
| of commands) for interacting with files, that way your code will work
| across different kinds of computers.

...

  |=====                                                               |   8%
| Let's jump right in so you can get a feel for how these special functions
| work!

...

  |=======                                                             |  10%
| Determine which directory your R session is using as its current working
| directory using getwd().

> getwd()
[1] "C:/Users/nastya/Documents/r1_"

| You are amazing!

  |=========                                                           |  13%
| List all the objects in your local workspace using ls().

> ls()
character(0)

| Excellent job!

  |==========                                                          |  15%
| Some R commands are the same as their equivalents commands on Linux or on a
| Mac. Both Linux and Mac operating systems are based on an operating system
| called Unix. It's always a good idea to learn more about Unix!

...

  |============                                                        |  18%
| Assign 9 to x using x <- 9.

> x <- 9

| Keep up the great work!

  |==============                                                      |  21%
| Now take a look at objects that are in your workspace using ls().

> ls()
[1] "x"

| Nice work!

  |================                                                    |  23%
| List all the files in your working directory using list.files() or dir().

> dir()
[1] "Lab1"      "r1_.Rproj" "README.md"

| You are amazing!

  |=================                                                   |  26%
| As we go through this lesson, you should be examining the help page for
| each new function. Check out the help page for list.files with the command
| ?list.files.

> ?list.files

| You nailed it! Good job!

  |===================                                                 |  28%
| One of the most helpful parts of any R help file is the See Also section.
| Read that section for list.files. Some of these functions may be used in
| later portions of this lesson.

...

  |=====================                                               |  31%
| Using the args() function on a function name is also a handy way to see
| what arguments a function can take.

...

  |=======================                                             |  33%
| Use the args() function to determine the arguments to list.files().

> args()
Ошибка в args() : аргумент "name" пропущен, умолчаний нет

> args(list.files())
NULL

| You're close...I can feel it! Try it again. Or, type info() for more
| options.

| Type args(list.files) to see the arguments to list.files.

> args(list.files)
function (path = ".", pattern = NULL, all.files = FALSE, full.names = FALSE, 
    recursive = FALSE, ignore.case = FALSE, include.dirs = FALSE, 
    no.. = FALSE) 
NULL

| You nailed it! Good job!

  |========================                                            |  36%
| Assign the value of the current working directory to a variable called
| "old.dir".

> 
> old.dir
Ошибка: объект 'old.dir' не найден

> old.dir <- getwd()

| That's the answer I was looking for.

  |==========================                                          |  38%
| We will use old.dir at the end of this lesson to move back to the place
| that we started. A lot of query functions like getwd() have the useful
| property that they return the answer to the question as a result of the
| function.

...

  |============================                                        |  41%
| Use dir.create() to create a directory in the current working directory
| called "testdir".

> dir.create(testdir)
Ошибка: объект 'testdir' не найден

> testdir.create()
Ошибка в testdir.create() : не могу найти функцию "testdir.create"

> dir.create("testdir")

| Keep up the great work!

  |==============================                                      |  44%
| We will do all our work in this new directory and then delete it after we
| are done. This is the R analog to "Take only pictures, leave only
| footprints."

...

  |===============================                                     |  46%
| Set your working directory to "testdir" with the setwd() command.

> setwd("testdir")

| You are doing so well!

  |=================================                                   |  49%
| In general, you will want your working directory to be someplace sensible,
| perhaps created for the specific project that you are working on. In fact,
| organizing your work in R packages using RStudio is an excellent option.
| Check out RStudio at http://www.rstudio.com/

...

  |===================================                                 |  51%
| Create a file in your working directory called "mytest.R" using the
| file.create() function.

> file.create("mytest.R")
[1] TRUE

| Great job!

  |=====================================                               |  54%
| This should be the only file in this newly created directory. Let's check
| this by listing all the files in the current directory.

> ls()
[1] "old.dir" "x"      

| Almost! Try again. Or, type info() for more options.

| list.files() shows that the directory only contains mytest.R.

> list.files()
[1] "mytest.R"

| You are quite good my friend!

  |======================================                              |  56%
| Check to see if "mytest.R" exists in the working directory using the
| file.exists() function.

> file.exists("mytest.R")
[1] TRUE

| You are amazing!

  |========================================                            |  59%
| These sorts of functions are excessive for interactive use. But, if you are
| running a program that loops through a series of files and does some
| processing on each one, you will want to check to see that each exists
| before you try to process it.

...

  |==========================================                          |  62%
| Access information about the file "mytest.R" by using file.info().

> file.info("mytest.R")
         size isdir mode               mtime               ctime
mytest.R    0 FALSE  666 2025-10-11 13:26:00 2025-10-11 13:26:00
                       atime exe  uname         udomain
mytest.R 2025-10-11 13:26:00  no nastya WIN-518F21652NA

| All that practice is paying off!

  |============================================                        |  64%
| You can use the $ operator --- e.g., file.info("mytest.R")$mode --- to grab
| specific items.

...

  |=============================================                       |  67%
| Change the name of the file "mytest.R" to "mytest2.R" by using
| file.rename().

> file.rename("mytest2.R")
Ошибка в file.rename("mytest2.R") : аргумент "to" пропущен, умолчаний нет

> file.rename("mytest.R" to "mytest2.R")
Ошибка: неожиданный символ в "file.rename("mytest.R" to"

> file.rename("mytest.R","mytest2.R")
[1] TRUE

| That's correct!

  |===============================================                     |  69%
| Your operating system will provide simpler tools for these sorts of tasks,
| but having the ability to manipulate files programatically is useful. You
| might now try to delete mytest.R using file.remove('mytest.R'), but that
| won't work since mytest.R no longer exists. You have already renamed it.

...

  |=================================================                   |  72%
| Make a copy of "mytest2.R" called "mytest3.R" using file.copy().

> file.copy("mytest2.R","mytest3.R")
[1] TRUE

| That's the answer I was looking for.

  |===================================================                 |  74%
| You now have two files in the current directory. That may not seem very
| interesting. But what if you were working with dozens, or millions, of
| individual files? In that case, being able to programatically act on many
| files would be absolutely necessary. Don't forget that you can,
| temporarily, leave the lesson by typing play() and then return by typing
| nxt().

...

  |====================================================                |  77%
| Provide the relative path to the file "mytest3.R" by using file.path().

> file.path("mytest3.R")
[1] "mytest3.R"

| You are quite good my friend!

  |======================================================              |  79%
| You can use file.path to construct file and directory paths that are
| independent of the operating system your R code is running on. Pass
| 'folder1' and 'folder2' as arguments to file.path to make a
| platform-independent pathname.

> file.path('folder1')
[1] "folder1"

| Not quite! Try again. Or, type info() for more options.

| file.path("folder1", "folder2") works.

> file.path("folder1", "folder2")
[1] "folder1/folder2"

| That's a job well done!

  |========================================================            |  82%
| Take a look at the documentation for dir.create by entering ?dir.create .
| Notice the 'recursive' argument. In order to create nested directories,
| 'recursive' must be set to TRUE.

